### ISSUE TITLE
Correctly Installed But Failed to Run (AttributeError: 'Meteor' object has no attribute 'meteor_p')

### ISSUE THREAD

**Issue by ChawDoe** [Maluuba/nlg-eval#101]
File "D:/PythonProjects/DataProcessing/eval.py", line 140, in eval
    metrics_dict = compute_individual_metrics(ref_lst[0][0], can_lst[0])
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\__init__.py", line 102, in compute_individual_metrics
    (Meteor(), "METEOR"),
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 53, in __init__
    stderr=subprocess.PIPE)
  File "D:\pythons\python3.7.4\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\pythons\python3.7.4\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <function Meteor.__del__ at 0x0000025588C0A4C8>
Traceback (most recent call last):
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 130, in __del__
    self.close()
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 59, in close
    if self.meteor_p:
AttributeError: 'Meteor' object has no attribute 'meteor_p'

![image](https://user-images.githubusercontent.com/25716030/87493365-3de84580-c67f-11ea-96bf-a3e1b406317d.png)

Java is also successfully installed
How can I solve this? Please help me!

**Comment by wutaiqiang** [comment]
https://github.com/Maluuba/nlg-eval/issues/95#issuecomment-658502196

**Comment by juharris** [comment]
It looks like it's having a problem running the Meteor JAR file: `FileNotFoundError: [WinError 2] 系统找不到指定的文件。`
What happens if you just run `where java` in your terminal?

**Comment by ChawDoe** [comment]
> It looks like it's having a problem running the Meteor JAR file: `FileNotFoundError: [WinError 2] 系统找不到指定的文件。`
> What happens if you just run `where java` in your terminal?

I download the Meteor JAR file, and add its directory in PATH.  The program can run successfully now.

**Comment by ChawDoe** [comment]
> [#95 (comment)](https://github.com/Maluuba/nlg-eval/issues/95#issuecomment-658502196)

The java command can run successfully. So it may not be the cause.
