### ISSUE TITLE
MemoryError: Unable to allocate 251. GiB for an array with shape (259660, 259660) and data type float32

### ISSUE THREAD

**Issue by TianHongZXY** [Maluuba/nlg-eval#111]
My hypothesis file and references file both hs 259660 lines, and it reports error when computing embedding scores, what should i do to make it run successfully?
```
Traceback (most recent call last):
  File "/home/zxy/anaconda3/bin/nlg-eval", line 216, in <module>
    compute_metrics()
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/zxy/anaconda3/bin/nlg-eval", line 208, in compute_metrics
    nlgeval.compute_metrics(hypothesis, references, no_overlap, no_skipthoughts, no_glove)
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/nlgeval/__init__.py", line 62, in compute_metrics
    cosine_similarity = list(map(lambda refv: cosine_similarity(refv, vector_hyps).diagonal(), vector_refs))
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/nlgeval/__init__.py", line 62, in <lambda>
    cosine_similarity = list(map(lambda refv: cosine_similarity(refv, vector_hyps).diagonal(), vector_refs))
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/sklearn/metrics/pairwise.py", line 1176, in cosine_similarity
    dense_output=dense_output)
  File "/home/zxy/anaconda3/lib/python3.7/site-packages/sklearn/utils/extmath.py", line 151, in safe_sparse_dot
    ret = a @ b
MemoryError: Unable to allocate 251. GiB for an array with shape (259660, 259660) and data type float32
```

**Comment by juharris** [comment]
Thanks for using our project! How about looping line by line? See "object oriented API for repeated calls in a script - single example" in the README.

**Comment by TianHongZXY** [comment]
Thank you for answering,  i think if i loop line by line and sum all each metrics_dict keys'values then divide the len(refences) and i will get the answer, is that right?
Also I fount looping line by line was just too slow, about 1.5 iter/s but i have 26w lines!  I'm using intel i9-7900X which has 10 cores and 20 threads, is there anyway to speed it up?

**Comment by juharris** [comment]
Running in batches would help. Also you can disable the metrics you don't care about as much. METEOR is likely one of the slower ones since it calls a Java process a few times.

**Comment by kracwarlock** [comment]
Yes, for embedding based metrics you can run them line-by-line or in batches and that will give you the right score. It is only for metrics like Bleu where the metric needs to be computed on the corpus level at once (corpus and sentence Bleu are going to be different).

**Comment by temporaer** [comment]
closing, likely resolved.
