### ISSUE TITLE
Getting " Unknown parameter type "  on model instantiation 

### ISSUE THREAD

**Issue by amit0623** [Maluuba/nlg-eval#128]
Traceback (most recent call last):
  File "eval.py", line 29, in <module>
    nlgeval = NLGEval()  # loads the evaluator
  File "/usr/local/lib/python3.7/dist-packages/nlgeval/__init__.py", line 202, in __init__
    self.load_skipthought_model()
  File "/usr/local/lib/python3.7/dist-packages/nlgeval/__init__.py", line 236, in load_skipthought_model
    model = skipthoughts.load_model()
  File "/usr/local/lib/python3.7/dist-packages/nlgeval/skipthoughts/skipthoughts.py", line 53, in load_model
    embedding, x_mask, ctxw2v = build_encoder(utparams, uoptions)
  File "/usr/local/lib/python3.7/dist-packages/nlgeval/skipthoughts/skipthoughts.py", line 312, in build_encoder
    mask=x_mask)
  File "/usr/local/lib/python3.7/dist-packages/nlgeval/skipthoughts/skipthoughts.py", line 437, in gru_layer
    strict=True)
  File "/usr/local/lib/python3.7/dist-packages/theano/scan_module/scan.py", line 849, in scan
    profile=False)
  File "/usr/local/lib/python3.7/dist-packages/theano/compile/function/__init__.py", line 350, in function
    output_keys=output_keys,
  File "/usr/local/lib/python3.7/dist-packages/theano/compile/function/pfunc.py", line 427, in pfunc
    _pfunc_param_to_in(p, allow_downcast=allow_input_downcast) for p in params
  File "/usr/local/lib/python3.7/dist-packages/theano/compile/function/pfunc.py", line 427, in <listcomp>
    _pfunc_param_to_in(p, allow_downcast=allow_input_downcast) for p in params
  File "/usr/local/lib/python3.7/dist-packages/theano/compile/function/pfunc.py", line 543, in _pfunc_param_to_in
    raise TypeError(f"Unknown parameter type: {type(param)}")
TypeError: Unknown parameter type: <class 'theano.tensor.var.TensorVariable'>

**Comment by juharris** [comment]
Duplicate of #127 ?

**Comment by amit0623** [comment]
@juharris - Can you share the resolution steps. I dont seem to find it in #127

**Comment by kracwarlock** [comment]
This seems like a theano version mismatch. Can you make sure you don't have a previous installation of theano that was not uninstalled?
