### ISSUE TITLE
Getting error "ValueError: could not convert string to float: '' 

### ISSUE THREAD

**Issue by bernardoleite** [Maluuba/nlg-eval#131]
Right after installing and setting up nlg-eval with success, I did the following test:

```
from nlgeval import NLGEval

nlgeval = NLGEval()  # loads the models
metrics_dict = nlgeval.compute_individual_metrics(['this is small test'], 'this is a test')
print(metrics_dict)
```

I'm getting the following error:
```
Error handling value: b''
Decoded value: 
eval_line: EVAL ||| 4.0 4.0 3.0 2.0 1.0 1.0 2.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 3.0 3.0
Traceback (most recent call last):
  File "/Users/bernardoleite/Desktop/project-folder/src/eval.py", line 27, in <module>
    run(args)
  File "/Users/bernardoleite/Desktop/project-folder/src/eval.py", line 13, in run
    metrics_dict = nlgeval.compute_individual_metrics(['this is small test'], 'this is a test')
  File "/Users/bernardoleite/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/nlgeval/__init__.py", line 259, in compute_individual_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "/Users/bernardoleite/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/nlgeval/pycocoevalcap/meteor/meteor.py", line 85, in compute_score
    scores.append(float(dec(v.strip())))
ValueError: could not convert string to float: ''
```
I am using Mac OS High Sierra with python 3.9.7.  
Does anyone have an idea what the problem could be? Thanks in advance.

**Comment by juharris** [comment]
You might find https://github.com/Maluuba/nlg-eval#troubleshooting or some suggestions in #64 helpful.
________________________________
From: bernardoleite ***@***.***>
Sent: March 17, 2022 05:57
To: Maluuba/nlg-eval ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Maluuba/nlg-eval] Getting error "ValueError: could not convert string to float: '' (Issue #131)


Right after installing and setting up nlg-eval with success, I did the following test:

from nlgeval import NLGEval

nlgeval = NLGEval()  # loads the models
metrics_dict = nlgeval.compute_individual_metrics(['this is small test'], 'this is a test')
print(metrics_dict)


I'm getting the following error:

Error handling value: b''
Decoded value:
eval_line: EVAL ||| 4.0 4.0 3.0 2.0 1.0 1.0 2.0 2.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 2.0 3.0 3.0
Traceback (most recent call last):
  File "/Users/bernardoleite/Desktop/project-folder/src/eval.py", line 27, in <module>
    run(args)
  File "/Users/bernardoleite/Desktop/project-folder/src/eval.py", line 13, in run
    metrics_dict = nlgeval.compute_individual_metrics(['this is small test'], 'this is a test')
  File "/Users/bernardoleite/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/nlgeval/__init__.py", line 259, in compute_individual_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "/Users/bernardoleite/opt/miniconda3/envs/myenv/lib/python3.9/site-packages/nlgeval/pycocoevalcap/meteor/meteor.py", line 85, in compute_score
    scores.append(float(dec(v.strip())))
ValueError: could not convert string to float: ''


I am using Mac OS High Sierra with python 3.9.7.
Does anyone have an idea what the problem could be? Thanks in advance.
