### ISSUE TITLE
download for glove 6B fails

### ISSUE THREAD

**Issue by dhansmair** [Maluuba/nlg-eval#133]
Hi there!
Installation of the package succeeds, but I get the following errors when running `nlg-eval --setup`:

```
Downloading http://nlp.stanford.edu/data/glove.6B.zip to /home/david/.cache/nlgeval.
```
[...]
```

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/david/.local/bin/nlg-eval", line 39, in _download_file
    r = requests.get(url, stream=True)
  File "/home/david/.local/lib/python3.8/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/requests/sessions.py", line 723, in send
    history = [resp for resp in gen]
  File "/home/david/.local/lib/python3.8/site-packages/requests/sessions.py", line 723, in <listcomp>
    history = [resp for resp in gen]
  File "/home/david/.local/lib/python3.8/site-packages/requests/sessions.py", line 266, in resolve_redirects
    resp = self.send(
  File "/home/david/.local/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='downloads.cs.stanford.edu', port=443): Max retries exceeded with url: /nlp/data/glove.6B.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe571ce9160>: Failed to establish a new connection: [Errno 110] Connection timed out'))
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/david/.local/bin/nlg-eval", line 214, in <module>
    setup()
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/.local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/.local/bin/nlg-eval", line 151, in setup
    pool.map(_download_file, downloads)
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
requests.exceptions.ConnectionError: None: Max retries exceeded with url: /nlp/data/glove.6B.zip (Caused by None)
```

apparently, `glove.6B.zip` does not exist anymore.

**Comment by juharris** [comment]
Thanks for bringing this to our attention. I can confirm that the download doesn't start in my browser when I use the link to http://nlp.stanford.edu/data/glove.6B.zip found on the project page at https://nlp.stanford.edu/projects/glove/.

**Comment by juharris** [comment]
There's a discussion in https://stackoverflow.com/questions/72736034 and https://github.com/stanfordnlp/GloVe/issues/206

**Comment by dhansmair** [comment]
A power outage, I see. I'll close this then. Thanks a lot!
