### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by Dyer233** [Maluuba/nlg-eval#136]
Traceback (most recent call last):
  File "/home/admin01/test-search/HS-B/eval/ast2code.py", line 367, in <module>
    nlgeval = NLGEval()
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/nlg_eval-2.3-py3.9.egg/nlgeval/__init__.py", line 202, in __init__
    self.load_skipthought_model()
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/nlg_eval-2.3-py3.9.egg/nlgeval/__init__.py", line 236, in load_skipthought_model
    model = skipthoughts.load_model()
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/nlg_eval-2.3-py3.9.egg/nlgeval/skipthoughts/skipthoughts.py", line 60, in load_model
    utable, btable = load_tables()
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/nlg_eval-2.3-py3.9.egg/nlgeval/skipthoughts/skipthoughts.py", line 81, in load_tables
    btable = numpy.load(os.path.join(path_to_tables, 'btable.npy'), allow_pickle=True,  encoding='bytes')
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/numpy/lib/npyio.py", line 440, in load
    return format.read_array(fid, allow_pickle=allow_pickle,
  File "/home/admin01/anaconda3/envs/pingu/lib/python3.9/site-packages/numpy/lib/format.py", line 748, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated

**Comment by juharris** [comment]
Thanks for trying out our library. Please validate that the setup was successful: https://github.com/Maluuba/nlg-eval#validate-the-setup-optional

**Comment by Dyer233** [comment]
![c1987e1803ff8d4a8add9a0e33ff6c7](https://user-images.githubusercontent.com/106246170/188355201-3471d9a3-1f29-4dd7-93b2-cd814ccab55a.jpg)
![3737eee7a85819d272d27b8f4c4e5d5](https://user-images.githubusercontent.com/106246170/188355288-50588360-ad76-45b9-b78c-57a43ee7b7bd.jpg)

All files have been downloaded, but this problem still occurs.
