### ISSUE TITLE
nlg-eval --setup  error  can't download glove.6B.zip

### ISSUE THREAD

**Issue by tytcc** [Maluuba/nlg-eval#147]
when run the command
```nlg-eval --setup```
i got the below error, it seems I can't download glove.6B.zip. How can I fix it?
```
Downloading https://raw.githubusercontent.com/robmsmt/glove-gensim/4c2224bccd61627b76c50a5e1d6afd1c82699d22/glove2word2vec.py to /Users/ccj/opt/anaconda3/lib/python3.9/site-packages/nlgeval/word2vec.
Downloading http://nlp.stanford.edu/data/glove.6B.zip to /Users/ccj/.cache/nlgeval.
glove2word2vec.py: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 1.00/1.00 [00:00<00:00, 471 chunks/s]
ERROR:root:Error downloading file, will retry in 60s.
Traceback (most recent call last):
  File "/Users/ccj/opt/anaconda3/bin/nlg-eval", line 40, in _download_file
    r.raise_for_status()
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cs.stanford.edu/srcf_404data/glove.6B.zip
Downloading http://nlp.stanford.edu/data/glove.6B.zip to /Users/ccj/.cache/nlgeval.
ERROR:root:Error downloading file, will retry in 60s.
Traceback (most recent call last):
  File "/Users/ccj/opt/anaconda3/bin/nlg-eval", line 40, in _download_file
    r.raise_for_status()
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cs.stanford.edu/srcf_404data/glove.6B.zip
Downloading http://nlp.stanford.edu/data/glove.6B.zip to /Users/ccj/.cache/nlgeval.
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/ccj/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/ccj/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/ccj/opt/anaconda3/bin/nlg-eval", line 40, in _download_file
    r.raise_for_status()
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cs.stanford.edu/srcf_404data/glove.6B.zip
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ccj/opt/anaconda3/bin/nlg-eval", line 214, in <module>
    setup()
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ccj/opt/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/ccj/opt/anaconda3/bin/nlg-eval", line 151, in setup
    pool.map(_download_file, downloads)
  File "/Users/ccj/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/Users/ccj/opt/anaconda3/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://cs.stanford.edu/srcf_404data/glove.6B.zip
```

**Comment by temporaer** [comment]
Looks like standford removed the [project page](https://nlp.stanford.edu/projects/glove/). Maybe you can find an alternative source?

**Comment by tytcc** [comment]
> Looks like standford removed the [project page](https://nlp.stanford.edu/projects/glove/). Maybe you can find an alternative source?

I downloaded glove.6B.zip on other website. but the file format seems not same as README.
what I downloaded is
<img width="150" alt="image" src="https://github.com/Maluuba/nlg-eval/assets/48144572/33405b68-62db-463c-bb61-755b3a38e19c">
but in README is
<img width="674" alt="image" src="https://github.com/Maluuba/nlg-eval/assets/48144572/ff05561c-3373-49d6-a901-e510064bac07">

Is that OK?

**Comment by tytcc** [comment]
> Looks like standford removed the [project page](https://nlp.stanford.edu/projects/glove/). Maybe you can find an alternative source?

Thanks a lot. I have download it from https://github.com/stanfordnlp/GloVe.

**Comment by temporaer** [comment]
@tytcc if you feel comfortable modifying the nlg-eval scripts so that they too download from the new location, I'd appreciate it a lot!
