### ISSUE TITLE
Theano dependency error while installing the module

### ISSUE THREAD

**Issue by PedemonteGiacomo** [Maluuba/nlg-eval#159]
When the building whell is forming for the Theano dependencies I get an error that cannot make me complete the installation of the module

```bash
Collecting Theano>=0.8.1 (from nlg-eval==2.4.1)
  Using cached Theano-1.0.5.tar.gz (2.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      C:\Users\giaco\AppData\Local\Temp\pip-install-a2vw12no\theano_68d8627c0b3142098d0d0469840d3f8d\versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\giaco\AppData\Local\Temp\pip-install-a2vw12no\theano_68d8627c0b3142098d0d0469840d3f8d\setup.py", line 74, in <module>
          version_data = versioneer.get_versions()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\giaco\AppData\Local\Temp\pip-install-a2vw12no\theano_68d8627c0b3142098d0d0469840d3f8d\versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\giaco\AppData\Local\Temp\pip-install-a2vw12no\theano_68d8627c0b3142098d0d0469840d3f8d\versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by PedemonteGiacomo** [comment]
I've solved by explicitly using a `pip install Theano==0.8.1` to avoid to take the newest version that has main refactoring that makes obtain the error. But this should be fixed! The requirements should be Theano==0.8.1 instead of Theano>=0.8.1

**Comment by CaptainMorgan12** [comment]
0.9.0 also works
