### ISSUE TITLE
bug(encdoing): TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by samarthsikand** [Maluuba/nlg-eval#21]
I tried to run the basic functional API for the entire corpus, and have been getting the `TypeError` for the Meteor metric calculation. I am using Anaconda on Win10 and have all the pre-requisites installed(java 1.8.0 etc). I am running this on Python 3.5.4.
```
>>> from nlgeval import compute_metrics
>>> metrics_dict = compute_metrics(hypothesis="data/quora/train_target_1.txt",references=["data/quora/train_source_1.txt"],no_skipthoughts=True,no_glove=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\derp\desktop\nlgeval\nlgeval\__init__.py", line 29, in compute_metrics
    (Meteor(), "METEOR"),
  File "c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py", line 29, in __init__
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'encoding'
```

I tried a few approaches to bypass this issue, like commenting out the kwargs in __init__ function of  `c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py` and explicitly encoding the strings that were being passed to `self.meteor_p.stdin.write` in _stat function.
```
def __init__(self):
        meteor_cmd = ['java', '-jar', '-Xmx2G', METEOR_JAR,
                      '-', '-', '-stdio', '-l', 'en', '-norm']
#        kwargs = dict()
#        if not six.PY2:
#            kwargs['encoding'] = 'utf-8'
        self.meteor_p = subprocess.Popen(meteor_cmd,
                                         cwd=os.path.dirname(os.path.abspath(__file__)),
                                         stdin=subprocess.PIPE,
                                         stdout=subprocess.PIPE,
                                         stderr=subprocess.PIPE)
#                                         ,**kwargs)
        # Used to guarantee thread safety
        self.lock = threading.Lock()
```
```
def _stat(self, hypothesis_str, reference_list):
        # SCORE ||| reference 1 words ||| reference n words ||| hypothesis words
        hypothesis_str = hypothesis_str.replace('|||', '').replace('  ', ' ')
        score_line = ' ||| '.join(('SCORE', ' ||| '.join(reference_list), hypothesis_str))
        self.meteor_p.stdin.write(score_line.encode(encoding='utf-8'))
        self.meteor_p.stdin.write('\n'.encode(encoding='utf-8'))
        self.meteor_p.stdin.flush()
        return self.meteor_p.stdout.readline().strip()
```
But then an different error is coming this time:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\derp\desktop\nlgeval\nlgeval\__init__.py", line 34, in compute_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py", line 42, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py", line 63, in _stat
    self.meteor_p.stdin.flush()
OSError: [Errno 22] Invalid argument
```

Any insights to these problems ?

**Comment by temporaer** [comment]
Thanks for the report, the `encoding` argument to `Popen` was only added in python3.6. Can you please try whether the `fix-python35-support` branch works for you?

**Comment by samarthsikand** [comment]
Hey, I tried with the `fix-python35-support` branch. But its now giving some other error.
```
>>> from nlgeval import compute_metrics
>>> met = compute_metrics(hypothesis='data/quora/train_target_1.txt',references=['data/quora/train_source_1.txt'],no_skipthoughts=True,no_glove=True)
Bleu_1: 0.584349
Bleu_2: 0.443172
Bleu_3: 0.366154
Bleu_4: 0.310754
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\derp\desktop\nlgeval\nlgeval\__init__.py", line 34, in compute_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py", line 41, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "c:\users\derp\desktop\nlgeval\nlgeval\pycocoevalcap\meteor\meteor.py", line 60, in _stat
    self.meteor_p.stdin.write(score_line)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by temporaer** [comment]
i updated the branch, please try again.

**Comment by samarthsikand** [comment]
Thanks ! Its working now.
```
>>> met = compute_metrics(hypothesis='data/quora/train_target_1.txt',references=['data/quora/train_source_1.txt'],no_skipthoughts=True,no_glove=True)
Bleu_1: 0.584349
Bleu_2: 0.443172
Bleu_3: 0.366154
Bleu_4: 0.310754
METEOR: 0.312217
ROUGE_L: 0.581271
CIDEr: 2.834182
```
