### ISSUE TITLE
AttributeError: 'Word2Vec' object has no attribute 'vocabulary'

### ISSUE THREAD

**Issue by pj-parag** [Maluuba/nlg-eval#41]
gensim 3.5.0

```
nlg-eval --hypothesis=examples/hyp.txt --references=examples/ref1.txt --references=examples/ref2.txt

Bleu_1: 0.550000
Bleu_2: 0.428174
Bleu_3: 0.284043
Bleu_4: 0.201143
METEOR: 0.295797
ROUGE_L: 0.522104
CIDEr: 1.242192
SkipThoughtsCosineSimilairty: 0.626149
Traceback (most recent call last):
  File "/data1/struct2text/nlg_eval_vm/nlgconda/bin/nlg-eval", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/data1/struct2text/nlg_eval_vm/nlg-eval/bin/nlg-eval", line 169, in <module>
    compute_metrics()
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/data1/struct2text/nlg_eval_vm/nlg-eval/bin/nlg-eval", line 165, in compute_metrics
    nlgeval.compute_metrics(hypothesis, references, no_overlap, no_skipthoughts, no_glove)
  File "/data1/struct2text/nlg_eval_vm/nlg-eval/nlgeval/__init__.py", line 73, in compute_metrics
    scores = eval_emb_metrics(glove_hyps, glove_refs)
  File "/data1/struct2text/nlg_eval_vm/nlg-eval/nlgeval/word2vec/evaluate.py", line 46, in eval_emb_metrics
    emb = Embedding()
  File "/data1/struct2text/nlg_eval_vm/nlg-eval/nlgeval/word2vec/evaluate.py", line 14, in __init__
    self.m = KeyedVectors.load(os.path.join(path, 'glove.6B.300d.model.bin'), mmap='r')
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 211, in load
    return super(BaseKeyedVectors, cls).load(fname_or_handle, **kwargs)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/gensim/utils.py", line 420, in load
    obj._load_specials(fname, mmap, compress, subname)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/gensim/utils.py", line 485, in _load_specials
    setattr(self, attrib, None)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/gensim/utils.py", line 1419, in new_func1
    return func(*args, **kwargs)
  File "/data1/struct2text/nlg_eval_vm/nlgconda/lib/python3.6/site-packages/gensim/models/base_any2vec.py", line 745, in cum_table
    self.vocabulary.cum_table = value
AttributeError: 'Word2Vec' object has no attribute 'vocabulary'
```
I also tried using gensim 3.4.0 but same error.

**Comment by pj-parag** [comment]
Made some changes which seems to be working fine: https://github.com/pj-parag/nlg-eval/commit/18bc10cfac2c6336e7ed3260ee42e254ea05e652

**Comment by juharris** [comment]
That's odd. It's fine for me with gensim 3.5.0 and works for on Travis.
What's the output of `pip freeze | grep gensim` ?

**Comment by pj-parag** [comment]
pip freeze | grep gensim
gensim==3.5.0

**Comment by temporaer** [comment]
is it possible that you're loading a `glove.6B.300d.model.bin` that was generated using an older version of either gensim, python, or nlg-eval? If unsure, can you delete it and (re-)run `nlg-eval --setup`?

**Comment by pj-parag** [comment]
oh.. something like that is the case. http://nlp.stanford.edu/data/wordvecs/glove.6B.zip was(is maybe) down, so I used my downloaded glove.txt files and ran generate_w2v_files.py over it, which was in 3.4.0 version(and things started failing after that). Finally, I had to move to gensim 3.5 leading to the code change which I posted.

**Comment by pj-parag** [comment]
Still, I generated .bin file in gensim 3.4.0 only. What's the catch?
