### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by anandmishra22** [Maluuba/nlg-eval#48]
metrics_dict = compute_individual_metrics("I hate you", "I love you")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scratchd/home/anand/KVQG/baselines/eval/nlg-eval/nlgeval/__init__.py", line 117, in compute_individual_metrics
    model = skipthoughts.load_model()
  File "/scratchd/home/anand/KVQG/baselines/eval/nlg-eval/nlgeval/skipthoughts/skipthoughts.py", line 59, in load_model
    utable, btable = load_tables()
  File "/scratchd/home/anand/KVQG/baselines/eval/nlg-eval/nlgeval/skipthoughts/skipthoughts.py", line 80, in load_tables
    btable = numpy.load(os.path.join(path_to_tables, 'btable.npy'), encoding='bytes')
  File "/home/anand/.local/lib/python3.5/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/anand/.local/lib/python3.5/site-packages/numpy/lib/format.py", line 647, in read_array
    array = pickle.load(fp, **pickle_kwargs)
EOFError: Ran out of input

**Comment by temporaer** [comment]
it looks like the download/installation routine did not finish correctly. Can you please delete the files it downloaded and run setup again?

**Comment by juharris** [comment]
You can find the setup instructions [here](https://github.com/Maluuba/nlg-eval#setup).

**Comment by juharris** [comment]
The `ref` parameter needs to be a list. You can find examples here: https://github.com/Maluuba/nlg-eval/blob/master/nlgeval/tests/test_nlgeval.py
