### ISSUE TITLE
OSError: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by samarthsikand** [Maluuba/nlg-eval#57]
I am running the basic functional API as in README. And I am running into the following error:
```
>>> from nlgeval import compute_metrics
>>> metrics_dict = compute_metrics(hypothesis='examples/hyp.txt',references=['examples/ref1.txt','examples/ref2.txt'])
Bleu_1: 0.550000
Bleu_2: 0.428174
Bleu_3: 0.284043
Bleu_4: 0.201143
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Back Up\Desktop\Setiment Analysis\nlg-eval\nlgeval\__init__.py", line 40, in compute_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "D:\Back Up\Desktop\Setiment Analysis\nlg-eval\nlgeval\pycocoevalcap\meteor\meteor.py", line 62, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "D:\Back Up\Desktop\Setiment Analysis\nlg-eval\nlgeval\pycocoevalcap\meteor\meteor.py", line 82, in _stat
    self.meteor_p.stdin.flush()
OSError: [Errno 22] Invalid argument
```

I thought this issue might be related to [Issue #8 ](https://github.com/Maluuba/nlg-eval/issues/8). So I uninstalled the ```scikit-learn``` using ```pip``` and reinstalled using ```conda```, but the issue still persists. I have all other perquisites installed( ```java version "1.8.0_201"```). I am using Anaconda on Win10 and Python 3.6.8. I'll post my ```conda list``` output just in case
```
# Name                    Version                   Build  Channel
absl-py                   0.7.0                     <pip>
astor                     0.7.1                     <pip>
blas                      1.0                         mkl
bleach                    1.5.0                     <pip>
boto                      2.49.0                    <pip>
boto3                     1.9.86                    <pip>
botocore                  1.12.86                   <pip>
bz2file                   0.98                      <pip>
certifi                   2018.11.29               py36_0
chardet                   3.0.4                     <pip>
Click                     7.0                       <pip>
docutils                  0.14                      <pip>
gast                      0.2.2                     <pip>
gensim                    3.7.0                     <pip>
grpcio                    1.18.0                    <pip>
html5lib                  0.9999999                 <pip>
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.8                       <pip>
intel-openmp              2019.1                      144
jmespath                  0.9.3                     <pip>
Markdown                  3.0.1                     <pip>
mkl                       2019.1                      144
mkl_fft                   1.0.10           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
nlg-eval                  2.1                       <pip>
nltk                      3.4                       <pip>
numpy                     1.15.4           py36h19fb1c0_0
numpy                     1.16.0                    <pip>
numpy-base                1.15.4           py36hc3f5095_0
pandas                    0.24.0                    <pip>
pip                       18.1                     py36_0
protobuf                  3.6.1                     <pip>
python                    3.6.8                h9f7ef89_0
python-dateutil           2.7.5                     <pip>
pytz                      2018.9                    <pip>
requests                  2.21.0                    <pip>
s3transfer                0.1.13                    <pip>
scikit-learn              0.20.2           py36h343c172_0
scipy                     1.2.0                     <pip>
scipy                     1.2.0            py36h29ff71c_0
setuptools                40.7.0                    <pip>
setuptools                40.6.3                   py36_0
singledispatch            3.4.0.3                   <pip>
six                       1.12.0                    <pip>
smart-open                1.8.0                     <pip>
sqlite                    3.26.0               he774522_0
tensorboard               1.8.0                     <pip>
tensorflow-gpu            1.8.0                     <pip>
termcolor                 1.1.0                     <pip>
Theano                    1.0.4                     <pip>
tqdm                      4.30.0                    <pip>
urllib3                   1.24.1                    <pip>
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
Werkzeug                  0.14.1                    <pip>
wheel                     0.32.3                   py36_0
wheel                     0.32.3                    <pip>
wincertstore              0.2              py36h7fe50ca_0
```
Earlier I got it to work it with Python 3.5 ( Issue #21 ). Where am I going wrong ?

**Comment by samarthsikand** [comment]
I ran the pdb debugger on my program and this is the output I am getting:
```
> d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py(2)<module>()
-> from nlgeval import NLGEval
(Pdb) n
> d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py(4)<module>()
-> nlgeval = NLGEval()
(Pdb) n
> d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py(5)<module>()
-> metrics_dict = nlgeval.compute_individual_metrics(['hello there','hey there'],'hello')
(Pdb) n
OSError: [Errno 22] Invalid argument
> d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py(5)<module>()
-> metrics_dict = nlgeval.compute_individual_metrics(['hello there','hey there'],'hello')
(Pdb) self.meteor_p.stderr.read()
*** NameError: name 'self' is not defined
(Pdb) n
--Return--
> d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py(5)<module>()->None
-> metrics_dict = nlgeval.compute_individual_metrics(['hello there','hey there'],'hello')
(Pdb) n
OSError: [Errno 22] Invalid argument
> <string>(1)<module>()->None
(Pdb) n
--Return--
> <string>(1)<module>()->None
(Pdb) n
Traceback (most recent call last):
  File "C:\Users\s.sikand\AppData\Local\conda\conda\envs\tensorflowGPU\lib\pdb.py", line 1667, in main
    pdb._runscript(mainpyfile)
  File "C:\Users\s.sikand\AppData\Local\conda\conda\envs\tensorflowGPU\lib\pdb.py", line 1548, in _runscript
    self.run(statement)
  File "C:\Users\s.sikand\AppData\Local\conda\conda\envs\tensorflowGPU\lib\bdb.py", line 434, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "d:\back up\desktop\setiment analysis\ulmfit-paraphrase\nlg_score_test.py", line 5, in <module>
    metrics_dict = nlgeval.compute_individual_metrics(['hello there','hey there'],'hello')
  File "d:\back up\desktop\setiment analysis\nlg-eval\nlgeval\__init__.py", line 249, in compute_individual_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "d:\back up\desktop\setiment analysis\nlg-eval\nlgeval\pycocoevalcap\meteor\meteor.py", line 62, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "d:\back up\desktop\setiment analysis\nlg-eval\nlgeval\pycocoevalcap\meteor\meteor.py", line 82, in _stat
    self.meteor_p.stdin.flush()
OSError: [Errno 22] Invalid argument
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> d:\back up\desktop\setiment analysis\nlg-eval\nlgeval\pycocoevalcap\meteor\meteor.py(82)_stat()
-> self.meteor_p.stdin.flush()
(Pdb) self.meteor_p.stderr.read()
b'Exception in thread "main" java.lang.RuntimeException: Error: file not found (file:/D:/Back%2520Up/Desktop/Setiment%2520Analysis/nlg-eval/nlgeval/pycocoevalcap/meteor/data/paraphrase-en.gz)\r\n\tat edu.cmu.meteor.aligner.ParaphraseTransducer.<init>(Unknown Source)\r\n\tat edu.cmu.meteor.aligner.Aligner.setupModules(Unknown Source)\r\n\tat edu.cmu.meteor.aligner.Aligner.<init>(Unknown Source)\r\n\tat edu.cmu.meteor.scorer.MeteorScorer.loadConfiguration(Unknown Source)\r\n\tat edu.cmu.meteor.scorer.MeteorScorer.<init>(Unknown Source)\r\n\tat Meteor.main(Unknown Source)\r\n'
(Pdb)
```
After running the ```self.meteor_p.stderr.read()```, it seems that some file ```paraphrase-en.gz``` is missing from the data folder. But I am pretty sure that I ran the ```nlg-eval --setup``` command from windows cmd as ```python bin/nlg-eval --setup``` and it downloaded the following files.
![issue](https://user-images.githubusercontent.com/16184715/52257138-6ecb3380-293f-11e9-9067-7b53aa35aec5.jpg)

What steps should I take now ?

**Comment by samarthsikand** [comment]
Yes, the ```nlgeval/pycocoevalcap/meteor/data/paraphrase-en.gz``` file was present. I uninstalled the project and reinstalled to a path with no spaces and it works (although very slow)  !!
```
(tensorflowGPU) D:\Back Up\Desktop\Setiment Analysis\ulmfit-paraphrase>python nlg_score_test.py
WARNING (theano.configdefaults): g++ not available, if using conda: `conda install m2w64-toolchain`
C:\Users\s.sikand\AppData\Local\conda\conda\envs\tensorflowGPU\lib\site-packages\theano\configdefaults.py:560: UserWarning: DeprecationWarning: there is no c++ compiler.This is deprecated and with Theano 0.11 a c++ compiler will be mandatory
  warnings.warn("DeprecationWarning: there is no c++ compiler."
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
{'Bleu_1': 0.3678794404356846, 'Bleu_2': 0.0003678794406196241, 'Bleu_3': 3.678794406809375e-05, 'Bleu_4': 1.163336936997511e-05, 'METEOR': 0.31168831168831174, 'ROUGE_L': 0.6288659793814433, 'CIDEr': 0.0, 'SkipThoughtCS': 0.5851747}
```

**Comment by samarthsikand** [comment]
I am closing this issue although I don't know whether spaces in path names should be handled or not while installing the project.

**Comment by temporaer** [comment]
thanks for confirming @samarthsikand! will keep a look out for this issue, but it might be a problem in a wrapped library (i don't think we urlencode any paths).
