### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by shaunakjoshi12** [Maluuba/nlg-eval#58]
```
Traceback (most recent call last):
  File "test_results.py", line 41, in <module>
    metrics_dict = nlgeval.compute_metrics(references, hypotheses)
  File "/home/shaunak/ProjectSSSP/FULL S/caption_generator_resnet/nlg_eval_master/nlgeval/__init__.py", line 292, in compute_metrics
    score, scores = scorer.compute_score(refs, hyps)
  File "/home/shaunak/ProjectSSSP/FULL S/caption_generator_resnet/nlg_eval_master/nlgeval/pycocoevalcap/meteor/meteor.py", line 62, in compute_score
    stat = self._stat(res[i][0], gts[i])
  File "/home/shaunak/ProjectSSSP/FULL S/caption_generator_resnet/nlg_eval_master/nlgeval/pycocoevalcap/meteor/meteor.py", line 84, in _stat
    self.meteor_p.stdin.write(score_line)
IOError: [Errno 32] Broken pipe
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/shaunak/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/shaunak/ProjectSSSP/FULL S/caption_generator_resnet/nlg_eval_master/nlgeval/pycocoevalcap/meteor/meteor.py", line 50, in close
    if atexit is not None and atexit.unregister is not None:
AttributeError: 'module' object has no attribute 'unregister'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/home/shaunak/anaconda2/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/shaunak/ProjectSSSP/FULL S/caption_generator_resnet/nlg_eval_master/nlgeval/pycocoevalcap/meteor/meteor.py", line 50, in close
    if atexit is not None and atexit.unregister is not None:
AttributeError: 'module' object has no attribute 'unregister'
```
In  'self.meteor_p.stdin.write(score_line)' ioerror32: Broken Pipe appears in meteor.py

**Comment by juharris** [comment]
The line numbers don't match up with the master branch. Would you `git pull origin master` and try again?

**Comment by juharris** [comment]
I'm pretty sure this has been corrected in master. Closing due to staleness.
