### ISSUE TITLE
_pickle.UnpicklingError: pickle data was truncated

### ISSUE THREAD

**Issue by AngusMonroe** [Maluuba/nlg-eval#60]
Hi, I've some problems when running `nlg-eval --hypothesis=examples/hyp.txt --references=examples/ref1.txt --references=examples/ref2.txt`:

First, it seems normal and output:

```
Bleu_1: 0.550000
Bleu_2: 0.428174
Bleu_3: 0.284043
Bleu_4: 0.201143
METEOR: 0.295797
ROUGE_L: 0.522104
CIDEr: 1.242192
```

And then I get a warning:

```
WARNING (theano.tensor.blas): We did not find a dynamic library in the library_dir of the library we use for blas. If you use ATLAS, make sure to compile it with dynamics library.
```

Finally, I get an abnormal program termination with '_pickle.UnpicklingError':

```
Traceback (most recent call last):
  File "/home/xjx/anaconda2/envs/anaconda-py3/bin/nlg-eval", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/xjx/nlg-eval/bin/nlg-eval", line 169, in <module>
    compute_metrics()
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/xjx/nlg-eval/bin/nlg-eval", line 165, in compute_metrics
    nlgeval.compute_metrics(hypothesis, references, no_overlap, no_skipthoughts, no_glove)
  File "/home/xjx/nlg-eval/nlgeval/__init__.py", line 55, in compute_metrics
    model = skipthoughts.load_model()
  File "/home/xjx/nlg-eval/nlgeval/skipthoughts/skipthoughts.py", line 59, in load_model
    utable, btable = load_tables()
  File "/home/xjx/nlg-eval/nlgeval/skipthoughts/skipthoughts.py", line 79, in load_tables
    utable = numpy.load(os.path.join(path_to_tables, 'utable.npy'), encoding='bytes')
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/numpy/lib/npyio.py", line 440, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/xjx/anaconda2/envs/anaconda-py3/lib/python3.6/site-packages/numpy/lib/format.py", line 693, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated
```

It would be helpful if someone know what should I do next.

Thanks and best regards!

**Comment by juharris** [comment]
Maybe some of the files didn't download properly?
Try deleting `nlgeval/data/utable.npy` and run the setup again.

**Comment by AngusMonroe** [comment]
I tried to remove that file and setup again. But the result doesn't change. It seems not work for me.

**Comment by juharris** [comment]
Can you share what the size of `nlgeval/data/utable.npy` is?
Mine:
```
$ ls -l nlgeval/data/utable.npy
-rwxrwxrwx 1 justin justin 2342138474 Sep 12  2018 nlgeval/data/utable.npy
```

**Comment by AngusMonroe** [comment]
Mine:
```
$ ls -l nlgeval/data/utable.npy
-rw-rw-r-- 1 xjx xjx 914358272 Mar 12 14:50 nlgeval/data/utable.npy
```

It seems that my file is missing. How can I correct the missing part?
I have tried reinstalling, but it didn't solve the problem.

**Comment by juharris** [comment]
That's weird. I guess you don't have a reliable internet connection?
You can try downloading the file manually in another way like `wget http://www.cs.toronto.edu/~rkiros/models/utable.npy` or through your browser (note some browsers don't handle big files well).

**Comment by juharris** [comment]
PS Sorry for my delayed responses. I was on vacation.

**Comment by AngusMonroe** [comment]
Thanks for your response. 

I successfully download `utable.npy` as your advice. Now this file size is correct:
```
$ ls -l nlgeval/data/utable.npy
-rw-rw-r-- 1 xjx xjx 2342138474 Jun 28  2015 nlgeval/data/utable.npy
```

But the error still exists.

**Comment by juharris** [comment]
Is it the exact some error? Maybe it's complaining about a different file now like `nlgeval/data/btable.npy`?

**Comment by juharris** [comment]
Closing since it's probably just an issue with downloading the file.

**Comment by AayushTyagi1** [comment]
I have the same error while using (x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()
I have tried downloading it all ways like manually too But it doesn't work.
I have good Internet connection.
