### ISSUE TITLE
OSError: 120000000 requested and 66581472 written

### ISSUE THREAD

**Issue by shinochin** [Maluuba/nlg-eval#70]
During executing `nlg-eval --setup`, OSError occurred.

The error message is as follows:

```
Traceback (most recent call last):
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/utils.py", line 692, in save
    _pickle.dump(self, fname_or_handle, protocol=pickle_protocol)
TypeError: file must have a 'write' attribute

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shinoda/.pyenv/versions/3.6.8/bin/nlg-eval", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/shinoda/app/nlg-eval/bin/nlg-eval", line 169, in <module>
    compute_metrics()
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 641, in make_context
    self.parse_args(ctx, args)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 940, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 1477, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/click/core.py", line 96, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/shinoda/app/nlg-eval/bin/nlg-eval", line 141, in setup
    generate()
  File "/home/shinoda/app/nlg-eval/nlgeval/word2vec/generate_w2v_files.py", line 26, in generate
    txt2bin(glove2word2vec(glove_vector_file, output_model_file))
  File "/home/shinoda/app/nlg-eval/nlgeval/word2vec/generate_w2v_files.py", line 17, in txt2bin
    m.save(filename.replace('txt', 'bin'), separately=None)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 435, in save
    super(WordEmbeddingsKeyedVectors, self).save(*args, **kwargs)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/models/keyedvectors.py", line 223, in save
    super(BaseKeyedVectors, self).save(fname_or_handle, **kwargs)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/utils.py", line 695, in save
    self._smart_save(fname_or_handle, separately, sep_limit, ignore, pickle_protocol=pickle_protocol)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/utils.py", line 547, in _smart_save
    compress, subname)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gensim/utils.py", line 621, in _save_specials
    np.save(subname(fname, attrib), np.ascontiguousarray(val))
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/numpy/lib/npyio.py", line 536, in save
    pickle_kwargs=pickle_kwargs)
  File "/home/shinoda/.pyenv/versions/3.6.8/lib/python3.6/site-packages/numpy/lib/format.py", line 644, in write_array
    array.tofile(fp)
OSError: 120000000 requested and 66581472 written
```

How can I solve this problem?

Thanks!

**Comment by shinochin** [comment]
It was a problem about the storage.
Sorry to distracting you.
