### ISSUE TITLE
post-setup crashes if nltk not installed

### ISSUE THREAD

**Issue by louismartin** [Maluuba/nlg-eval#77]
When installing nlg-eval with `pip install nlg-eval@git+https://github.com/Maluuba/nlg-eval.git` and if `nltk` is not installed, the following exception is raised by https://github.com/Maluuba/nlg-eval/blob/5a89faf7d3e0ed2d630f261b7f62d4cc2ba49eb6/setup.py#L19-L21

```
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-v3k3eqaa/nlg-eval/setup.py", line 56, in <module>
      'install': PostInstallCommand,
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 228, in run
      self.run_command('install')
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/private/home/louismartin/miniconda3/envs/tmp/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-v3k3eqaa/nlg-eval/setup.py", line 34, in run
      _post_setup()
    File "/tmp/pip-install-v3k3eqaa/nlg-eval/setup.py", line 20, in _post_setup
      from nltk.downloader import download
  ModuleNotFoundError: No module named 'nltk'
  ----------------------------------------
  ERROR: Failed building wheel for nlg-eval
```

This error prevents the automatic install of nlg-eval as a requirement in https://github.com/facebookresearch/text-simplification-evaluation/blob/21308789a173762af000ae9d8afedb356e0ae548/setup.py#L42

What would be the easiest way to fix it?

**Comment by juharris** [comment]
Thanks for the feedback!

That's odd but there will be other issues with installing that way anyway. For now we assume that the folder is cloned and installed from source because some other files are required for the download. We'd like to support it but it's just not a priority for us now.

I've created #78 to track the enhancement.

**Comment by juharris** [comment]
You should be able to pip install from a URL now. Check out the setup steps here: https://github.com/Maluuba/nlg-eval#setup
