### ISSUE TITLE
maybe something wrong with nlg-eval --setup

### ISSUE THREAD

**Issue by fishfishson** [Maluuba/nlg-eval#83]
I run the command `nlg-eval --setup` and it turns out like this:
```
Traceback (most recent call last):
  File "/home/xxx/anaconda3/bin/nlg-eval", line 214, in <module>
    setup()
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxx/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/xxx/anaconda3/bin/nlg-eval", line 157, in setup
    with ZipFile(os.path.join(data_path, 'glove.6B.zip')) as z:
  File "/home/xxx/anaconda3/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/home/xxx/anaconda3/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```
I check the file glove.6B.zip in .cache, finding it is damaged. After replacing the file with the one downloaded from official website, the command works well. So maybe there is something wrong with the download part. I am not sure.

**Comment by kracwarlock** [comment]
This was possibly a one-off downloading error. I am not able to reproduce this. Did you try the `nlg-eval --setup` command again by any chance?

**Comment by kracwarlock** [comment]
Closing due to inactivity. Please re-open if the issue is not resolved.
