### ISSUE TITLE
METEOR issue

### ISSUE THREAD

**Issue by gaobb** [Maluuba/nlg-eval#95]
$ nlg-eval --hypothesis=examples/hyp.txt --references=examples/ref1.txt --references=examples/ref2.txt

The error message is as follows:

Traceback (most recent call last):
  File "/usr/local/bin/nlg-eval", line 172, in <module>
    compute_metrics()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/nlg-eval", line 168, in compute_metrics
    nlgeval.compute_metrics(hypothesis, references, no_overlap, no_skipthoughts, no_glove)
  File "./nlg-eval-master/nlgeval/__init__.py", line 35, in compute_metrics
    (Meteor(), "METEOR"),
  File "./nlg-eval-master/nlgeval/pycocoevalcap/meteor/meteor.py", line 38, in __init__
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by gaobb** [comment]
The issue has been fixed by installing java

**Comment by wutaiqiang** [comment]
installl JDK？i tried that and it did not work

**Comment by ChawDoe** [comment]
> The issue has been fixed by installing java

I tried that and it also did not work.

**Comment by ChawDoe** [comment]
> > The issue has been fixed by installing java
> 
> I tried that and it also did not work.  

File "D:/PythonProjects/DataProcessing/eval.py", line 140, in eval
    metrics_dict = compute_individual_metrics(ref_lst[0][0], can_lst[0])
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\__init__.py", line 102, in compute_individual_metrics
    (Meteor(), "METEOR"),
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 53, in __init__
    stderr=subprocess.PIPE)
  File "D:\pythons\python3.7.4\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\pythons\python3.7.4\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Exception ignored in: <function Meteor.__del__ at 0x0000025588C0A4C8>
Traceback (most recent call last):
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 130, in __del__
    self.close()
  File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 59, in close
    if self.meteor_p:
AttributeError: 'Meteor' object has no attribute 'meteor_p'

**Comment by wutaiqiang** [comment]
> > > The issue has been fixed by installing java
> > 
> > 
> > I tried that and it also did not work.
> 
> File "D:/PythonProjects/DataProcessing/eval.py", line 140, in eval
> metrics_dict = compute_individual_metrics(ref_lst[0][0], can_lst[0])
> File "D:\pythons\python3.7.4\lib\site-packages\nlgeval__init__.py", line 102, in compute_individual_metrics
> (Meteor(), "METEOR"),
> File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 53, in **init**
> stderr=subprocess.PIPE)
> File "D:\pythons\python3.7.4\lib\subprocess.py", line 775, in **init**
> restore_signals, start_new_session)
> File "D:\pythons\python3.7.4\lib\subprocess.py", line 1178, in _execute_child
> startupinfo)
> FileNotFoundError: [WinError 2] 系统找不到指定的文件。
> Exception ignored in: <function Meteor.**del** at 0x0000025588C0A4C8>
> Traceback (most recent call last):
> File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 130, in **del**
> self.close()
> File "D:\pythons\python3.7.4\lib\site-packages\nlgeval\pycocoevalcap\meteor\meteor.py", line 59, in close
> if self.meteor_p:
> AttributeError: 'Meteor' object has no attribute 'meteor_p'
i solved that problem and write an essay in ZHIHU
https://zhuanlan.zhihu.com/p/159204903
it is in Chinese

**Comment by juharris** [comment]
To fully "install" Java, make sure that `javac` and `java` command are available in your PATH. Try running `javac -h` and `java -h` to check.

**Comment by ChawDoe** [comment]
> To fully "install" Java, make sure that `javac` and `java` command are available in your PATH. Try running `javac -h` and `java -h` to check.

Thank you. Problem solved.

**Comment by jack-wxm** [comment]
> > To fully "install" Java, make sure that `javac` and `java` command are available in your PATH. Try running `javac -h` and `java -h` to check.
> 
> Thank you. Problem solved.

how solved? I haved successfully installed jdk, but still have this problem. I also restart the environment file.
