### ISSUE TITLE
pip installation error

### ISSUE THREAD

**Issue by mshaikh2** [Maluuba/nlg-eval#97]
while trying to run the command
`pip install git+https://github.com/Maluuba/nlg-eval.git@master`
I get error as:
```
ERROR: Command errored out with exit status 1:
     command: /home/mshaikh2/anaconda3/envs/tf-gpu/bin/python3.5 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-4t0hee9u/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-4t0hee9u/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-f77lviyt
         cwd: /tmp/pip-req-build-4t0hee9u/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4t0hee9u/setup.py", line 24, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-req-build-4t0hee9u/setup.py", line 24, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Please help me fix it, as I need to use all the evaluations.

**Comment by juharris** [comment]
Thanks for pointing this out. It seems like pip or something might have changed since I can reproduce this after updating pip.

I believe I have solved this and I am testing it now but I would like you to try it too please just to confirm that it solves your issue. All you have to do is change the install command: `pip install git+https://github.com/Maluuba/nlg-eval.git@setup-pip-req`. If that works for you then we can merge the change in.

**Comment by mshaikh2** [comment]
Thanks this pip installation worked.

Now the issue is in setup


I am running the command for custom setup:
`nlg-eval --setup /media/MyDataStor1/mshaikh2/nlg_eval_data/`

and I get this error:

```
bi_skip.npz: 100%|████████████████████████| 276/276 [00:32<00:00, 8.44 chunks/s]
Traceback (most recent call last):
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/bin/nlg-eval", line 214, in <module>
    setup()
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/bin/nlg-eval", line 157, in setup
    with ZipFile(os.path.join(data_path, 'glove.6B.zip')) as z:
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/home/mshaikh2/anaconda3/envs/tf-gpu/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by juharris** [comment]
It's possible that some files failed to download. You should see a line in the logs like:
`In case of incomplete downloads, delete the directory and run `nlg-eval --setup /media/MyDataStor1/mshaikh2/nlg_eval_data/' again.`

**Comment by mshaikh2** [comment]
Thanks for your help again, following the instructions and rerunning the setup fixed the files.
However, I now have an assertion error!

I am using the script for multiple examples:
```
from nlgeval import NLGEval
nlgeval = NLGEval()  # loads the models
metrics_dict = nlgeval.compute_metrics(references, hypothesis)
```
Below are two reference sentences corresponding to two hypothesis sentences respectively, i.e. ref[0] corresponds to hyp[0] and ref[1] corresponds to hyp[1]:

```
references = ['heart size within normal limits. no typical findings of pulmonary edema. no pneumothorax.',
  'cardiac size within normal limits. no focal consolidation or pneumothorax. the visualized osseous structures appear intact.']
```
 ```
hypothesis = ['both lungs are clear bilaterally . specifically , no evidence of focal consolidation , pneumothorax , or pleural effusion . cardiomediastinal silhouette is unremarkable . visualized osseous structures appear intact . there are no acute bony abnormality .',
  'both lungs are clear bilaterally . specifically , no evidence of focal consolidation , pneumothorax , or pleural effusion . cardiomediastinal silhouette is unremarkable . visualized osseous structures appear intact . no acute bony abnormality .']
```

I get an assertion error:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-129-06535c64bccb> in <module>()
----> 1 metrics_dict = nlgeval.compute_metrics(references, hypothesis)

~/anaconda3/envs/tf-gpu/lib/python3.5/site-packages/nlgeval/__init__.py in compute_metrics(self, ref_list, hyp_list)
    290         refs = {idx: strippedlines for (idx, strippedlines) in enumerate(ref_list)}
    291         hyps = {idx: [lines.strip()] for (idx, lines) in enumerate(hyp_list)}
--> 292         assert len(refs) == len(hyps)
    293 
    294         ret_scores = {}

AssertionError: 
```

**Comment by juharris** [comment]
Please see the documentation for that method: https://docs.google.com/document/d/1Zf1iopOn4z9wmGO-MV34LQwlLe01Ma5vyzk-k48sg9A/edit?usp=sharing
references must be a list of lists of strings

**Comment by mshaikh2** [comment]
The attached document talks about pets and pee.
Can you kindly send me the reference doc.
Thanks in advance for fixing the issues.

**Comment by juharris** [comment]
lol I noticed right after I submitted sorry. I'm getting a puppy this weekend so those are some of my notes. I changed the link in my comment but I guess you didn't get notified. Here it is again: https://github.com/Maluuba/nlg-eval#object-oriented-api-for-repeated-calls-in-a-script---multiple-examples
